docapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='docapp'
urlpatterns = [
    path("", views.index, name="index"),
    path("newdoc",views.newdoc, name="newdoc"),


    ############ URLS for page showing the list of Documents #############

    path("doclist/<str:person_type>",views.doclist,name="doc_list"),
    path("doclist/<str:person_type>/filtered", views.doclist_filtered, name="doc_list_filtered"),

    #######################################################################

    ############ URLS for page showing the details of a Document #############
    path("docdetails/<int:doc_id>", views.docdetails, name="docdetails"),
    
    # URLS for editing/adding details of a document

    ### BASIC DETAILS ##############
    path("doceditbasic/<int:doc_id>", views.doceditbasic, name="doceditbasic"),
    path("docgetbasic/<int:doc_id>", views.docgetbasic, name="docgetbasic"),
    ###############################

    ### KEYWORDS ##################
    path("doceditkeywords/<int:doc_id>",  views.doceditkeywords, name="doceditkeywords"),
    path("docgetkeywords/<int:doc_id>", views.docgetkeywords, name="docgetkeywords"),
    ################################

    ### ENTITY_REPORT_TYPE #######
    path("doceditprojectreporttype/<int:doc_id>", views.doceditentityreporttype, name="doceditentityreporttype"),
    path("docgetprojectreporttype/<int:doc_id>", views.docgetentityreporttype, name="docgetentityreporttype"),
    ###############################

    ### PERSON TYPE ##############
    path("doceditpersontype/<int:doc_id>/<str:person_type>", views.doceditpersontype, name="doceditpersontype"),
    path("docgetpersontype/<int:doc_id>/<str:person_type>", views.docgetpersontype, name="docgetpersontype"),
    path("docpersonnewform/<str:person_type>", views.doceditpersontype_get_blank_form, name="docpersonnewform"),
    path("docpersondelete/<int:docrolemapping_id>", views.docdeleteperson, name="docpersondelete" ),
    ###############################

    ### PAGES & REFERENCES ########
    path("doceditpagesreferences/<int:doc_id>", views.doceditpagesreferences, name="doceditpagesreferences"),
    path("docgetpagesreferences/<int:doc_id>", views.docgetpagesreferences, name="docgetpagesreferences"),

    ###############################
    

    path("docgeneratenumber/<int:doc_id>", views.docgeneratenumber, name="docgeneratenumber"),
    path("docupload/<int:doc_id>", views.docupload, name="docupload" ),
    ####################################

    path("submittolibrary/<int:doc_id>", views.submit_to_library, name="libsubmit"),
    path("viewdocument/<int:doc_id>", views.viewdocument, name="viewdocument"),
    path("viewpdfthumbnail/<int:doc_id>",views.viewpdfthumbnail, name="viewdocumentthumbnail"),
    
    ###################################

    path("docwithdraw/<int:doc_id>", views.docwithdraw, name="docwithdraw"),
    path("dateextension/<int:doc_id>", views.dateextension, name="dateextension"),

    ###################################

    path("settings", views.docsettings, name="docsettings"),

    ###############################
    path("error", views.error,name="error"),

    ################################
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docnumber_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docnumberapp/', include("docapp.urls"))
]

docapp/views.py
from django.shortcuts import redirect, render

from docapp.constants import DOC_NUMBER_DRAFT, DOC_NUMBER_STATUSES, DOC_NUMBER_USED, DOCUMENT_STATUSES, MEMBER_TYPES, DOCUMENT_ROLES, PDF_FILE_LOCATION
from docapp.constants import AUTHOR_CONSTANT, REVIEWER_CONSTANT, APPROVER_CONSTANT, CHECKED_BY_CONSTANT
from docapp.constants import AUTHOR_TEXT,REVIEWER_TEXT,APPROVER_TEXT,CHECKED_BY_TEXT, PERSON_CONSTANT_TO_TEXT_MAPPING
from docapp.constants import DOCUMENT_CONSTANT_TO_DB_MAPPING
from docapp.constants import DOC_DRAFT,DOC_PENDING_UPLOAD,DOC_UNDER_REVIEW,DOC_REUPLOAD,DOC_NUMBER_WITHDRAWN,DOC_COMPLETED
from docapp.constants import DOC_AUTHOR_CONSTANT, DOC_CHECKED_CONSTANT, DOC_APPROVER_CONSTANT, DOC_REVIEWER_CONSTANT
from docapp.constants import DOCUMENT_LIST_PAGE_SIZE, PDF_THUMBNAIL_LOCATION, NUM_EXTENSIONS_DAYS, LIMIT_EXTENSIONS

from .models import DocNumberSequence, Document, DocKeywordMapping, DocumentRoles, DocumentStatus, Employee, Keywords, DocumentNumber
from .models import DocumentNumberStatus, DocRoleMapping
from .forms import DocumentCreationForm, DocumentTitleAbstractForm, DocumentUploadForm
from .forms import DocumentKeywordsForm, DocumentEntityReportTypeForm, DocumentPagesReferencesForm
from .forms import DocumentAdvancedSearch, DocumentNumberSearch, DocumentPersonForm
from .forms import DocumentPersonBaseFormSet
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404

from django.forms import formset_factory
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator
from django.db import transaction
from django.urls import reverse
from django.conf import settings
import hashlib
import os
import fitz
# Create your views here.

#### Some View Related Constants ############

REDIRECT_URL = "docdetails/{0}"

# Dont change the left hand side of the dictionary
HX_TRIGGERS = {
    "basicdetails": "basicdetailschanged",
    "entityreporttype": "entityreporttypechanged",
    "keywords" : "keywordschanged",
    "pagesreferences": "pagesreferenceschanged",
    AUTHOR_CONSTANT : "authorschanged",
    REVIEWER_CONSTANT : "reviewerschanged",
    APPROVER_CONSTANT : "approverschanged",
    CHECKED_BY_CONSTANT : "checkedbychanged"
}

ADVANCED_SEARCH_FORM_SUBMIT_ID = 'advancedsearch_submit'
SIMPLE_SEARCH_FORM_SUBMIT_ID = 'simplesearch_submit'
ADVANCED_SEARCH_FORM_HIDDEN_FIELD = 'advancedsearch_form_hidden'
SIMPLE_SEARCH_FORM_HIDDEN_FIELD = 'simplesearch_form_hidden'

#ADVANCED_SEARCH_TOGGLE_NAME = 'search_toggle_button_hidden'
ADVANCED_SEARCH_TOGGLE_NAME = 'search_toggle_button'

##########################################


def index(request):
    return render(request, "docapp/index.html", {})


def save_people_data(formset, person_type, doc_id):
    try:
        person_db_value = DOCUMENT_CONSTANT_TO_DB_MAPPING[person_type]
        document = Document.objects.get(doc_id = doc_id)
        document_role = DocumentRoles.objects.filter(doc_role_short_code=person_db_value).first()

        formset_cleaned_data = []
        for form in formset:
            if 'DELETE' in form.cleaned_data:
                if (not form.cleaned_data['DELETE']):
                    formset_cleaned_data.append(form.cleaned_data)
            else:
                formset_cleaned_data.append(form.cleaned_data)          
                
        for form_data in formset_cleaned_data:
            if 'person' in form_data:
                person_doc_role = DocRoleMapping(
                    doc=document,
                    emp=form_data['person'],
                    empdisplay_name = "",
                    role=document_role,
                    print_order=form_data['print_order'],
                    role_status = 1
                ) 
                person_doc_role.save()
        return True
    except:
        return False

def generate_document_sequence_number(project, doc_type, current_year):
    
    STARTING_SEQUENCE_NUMBER = 1000
    try:
        docnumber_sequence = DocNumberSequence.objects.get(
                                doc_project = project,
                                doc_type = doc_type,
                                doc_year = current_year,
                                doc_sequence_active = 1
                            )
    except:
        docnumber_sequence = None
    
    if(docnumber_sequence is None):
        docnumber_sequence = DocNumberSequence(
                        doc_project = project,
                        doc_type = doc_type,
                        doc_year = current_year,
                        doc_sequence_active = 1,
                        doc_sequence_number = STARTING_SEQUENCE_NUMBER
            )
        docnumber_sequence.save()
    
    sequence_number =  docnumber_sequence.doc_sequence_number
    docnumber_sequence.doc_sequence_number = docnumber_sequence.doc_sequence_number + 1
    docnumber_sequence.save()

    return sequence_number

def get_non_field_form_error_messages(request,form, is_formset=True ):
    error_messages = []
    if is_formset:
        errors_list = form.non_form_errors()
    else:
        errors_list = form.non_field_errors()
    for error in errors_list:
        messages.add_message(request,messages.ERROR,error)
    
def handle_file_upload(doc_id,file):
    document = Document.objects.get(doc_id = doc_id)
    
    m = hashlib.sha256()
    document_number = document.document_number
    document_number = document_number.replace("/","_")

    # Hash for document content
    content_to_encrypt = document_number + "_" + document.doc_title + "#" + document.abstract
    m.update(str.encode(content_to_encrypt))
    hex_digest = m.hexdigest()

    file_name = document_number + "_" + hex_digest + ".pdf"
    complete_path = os.path.join(PDF_FILE_LOCATION,file_name)
    if not os.path.exists(PDF_FILE_LOCATION):
        os.makedirs(PDF_FILE_LOCATION)
        
    with open(complete_path,"wb+") as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    
    # Generate Thumbnail
    pdf_document = fitz.open(complete_path)
    first_page = pdf_document[0]
    rect = fitz.Rect(0, 0, first_page.rect.width,first_page.rect.height)
    #first_page.add_rect_annot(rect)
    shape=first_page.new_shape()
    shape.draw_rect(rect)
    shape.finish(color=(0, 0, 0),width=2.5)
    shape.commit()
    image = first_page.get_pixmap()
    if not os.path.exists(PDF_THUMBNAIL_LOCATION):
        os.makedirs(PDF_THUMBNAIL_LOCATION)    

    image_path = os.path.join(PDF_THUMBNAIL_LOCATION,document_number + ".png")
    image.save(image_path)
    
    return (complete_path,image_path)

def newdoc(request):
    if request.method == "POST":
        form  = DocumentCreationForm(request.POST)
        report_type_form = DocumentEntityReportTypeForm(request.POST)
        
        DocumentPersonFormSet = formset_factory(DocumentPersonForm,formset=DocumentPersonBaseFormSet,extra=1, can_delete=True)
        author_formset = DocumentPersonFormSet(request.POST, prefix=AUTHOR_CONSTANT)
        reviewer_formset = DocumentPersonFormSet(request.POST,prefix = REVIEWER_CONSTANT)
        approver_formset = DocumentPersonFormSet(request.POST, prefix=APPROVER_CONSTANT)
        checkedby_formset = DocumentPersonFormSet(request.POST,prefix=CHECKED_BY_CONSTANT)

        # Reduce the below paragraph of code with a few lines
        form_valid = form.is_valid()
        report_type_form_valid = report_type_form.is_valid()
        author_formset_valid = author_formset.is_valid()
        reviewer_formset_valid = reviewer_formset.is_valid()
        approver_formset_valid = approver_formset.is_valid()
        # IGNORED AS OF NOW
        checkedby_formset_valid = checkedby_formset.is_valid()
        
        # Check if all entries are true
        if(form_valid==report_type_form_valid==author_formset_valid==reviewer_formset_valid==approver_formset_valid==True):

            doc_status_object = None
            doc_number_status_object = None
          
            if 'generate' in request.POST:
                doc_status_object = DocumentStatus.objects.get(doc_status_name=DOCUMENT_STATUSES[1][0])
                doc_number_status_object = DocumentNumberStatus.objects.get(doc_num_status_name=DOC_NUMBER_STATUSES[1][0])
            else:
                doc_status_object = DocumentStatus.objects.get(doc_status_name=DOCUMENT_STATUSES[0][0])
                doc_number_status_object = DocumentNumberStatus.objects.get(doc_num_status_name=DOC_NUMBER_STATUSES[0][0] )

            try:
                with transaction.atomic():
                        new_document = Document.objects.create(
                            doc_title=form.cleaned_data['doc_title'],
                            control_status=form.cleaned_data['control_status'],
                            security_classification=form.cleaned_data['security_classification'],
                            doc_type_general=form.cleaned_data['doc_type_general'],
                            doc_status=doc_status_object
                        )

                        new_document.parent_doc = new_document
                        new_document.save()

                        save_people_data(author_formset,AUTHOR_CONSTANT,new_document.doc_id)
                        save_people_data(reviewer_formset,REVIEWER_CONSTANT,new_document.doc_id)
                        save_people_data(approver_formset,APPROVER_CONSTANT,new_document.doc_id)
                        
                        if('generate' in request.POST):
                            current_year = timezone.now().year
                            sequence_number = generate_document_sequence_number(report_type_form.cleaned_data['doc_project'],report_type_form.cleaned_data['doc_type'],current_year)
                            doc_number = DocumentNumber.objects.create(
                                doc=new_document,

docapp/templates/docapp/doc_details_page_templates/doc_keywords.html
<b>Keywords</b> :
{% if keywords|length == 0 %}
    <span class="text-danger text-small">Add Keywords for the Document</span>
{% else %}
    {% for keyword in keywords %}
    <span class="badge bg-success">{{ keyword.keyword.keyword_name }}</span>
    {% endfor %}
{% endif %}

       

docapp/templates/docapp/doc_details_page_templates/doc_keywords_modal_form.html
<div class="modal-header">
    <h2 class="h6 modal-title">Add/Delete Keywords</h2><button type="button" class="btn-close" data-bs-dismiss="modal"
        aria-label="Close"></button>
</div>
<form hx-post="{% url 'docapp:doceditkeywords' doc_id=doc_id%}">
    {% csrf_token %}
    <div class="modal-body">
    <p class="card-text">
            {{ keywords_form }}
    </p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-secondary">Submit</button>
        <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
    </div>
</form>

docapp/templates/docapp/doc_details_page_templates/doc_pages_references.html
<div class="card-body">
    <div class="row">
        <div class="col-sm-3 mb-3">
            <div class="form-group">
                <label for="num_pages">Number of Pages</label>
                <input style="pointer-events: none;" class="form-control" id="num_pages"
                    type="text" value="{{doc.doc_num_page}}" required="">
            </div>
        </div>
        <div class="col-sm-3 mb-3">
            <div class="form-group">
                <label for="num_references">Number of References</label>
                <input style="pointer-events: none;" class="form-control" id="num_references"
                    type="text" value="{{doc.num_references}}" required="">
            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>

docapp/templates/docapp/doc_details_page_templates/doc_pages_references_modal_form.html
<div class="modal-header">
    <h2 class="h6 modal-title">Number of Pages & References</h2><button type="button" class="btn-close"
        data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form hx-post="{% url 'docapp:doceditpagesreferences' doc_id %}">
    {% csrf_token %}
    <div class="modal-body">
        <p class="card-text">        
            <div class="row mb-3">
                <div class="col-12 col-lg-6 col-sm-6 mb-1">
                    <label class="my-1 me-1" for="{{ document_pages_references_form.doc_num_page.id_for_label }}">Number of Pages</label>
                    {{ document_pages_references_form.doc_num_page }}
                    <div class="invalid-feedback">
                        {{ document_pages_references_form.doc_num_page.errors }}
                    </div>
                </div>
                <div class="col-12 col-lg-6 col-sm-6 mb-1">
                    <label class="my-1 me-2" for="{{ document_pages_references_form.num_references.id_for_label }}">Number of References</label>
                    {{ document_pages_references_form.num_references }}
                    <div class="invalid-feedback">
                        {{ document_pages_references_form.num_references.errors }}
                    </div>
                </div>
            </div>
        </p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-secondary">Submit</button>
        <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
    </div>
</form>

docapp/templates/docapp/doc_details_page_templates/doc_peoples.html
{% load static %}
<div class="card-body">
    <ul class="list-group list-group-flush list my--3">
        
        {% for person in people %}
            <li style="background-color: inherit; border-bottom: solid 1px #b1b1b1 !important;" class="list-group-item px-0 border-bottom">
                <div class="d-flex align-items-center justify-content-start">
                    <div class="me-3"> <img class="rounded avatar-lg"
                            src="{% static 'docapp/assets/img/team/profile-picture-1.jpg' %}" alt="change avatar">
                    </div>

                    <div class="d-flex justify-content-xl-center ms-xl-3">
                        <div class="d-flex">
                            <div class="d-md-block text-left">
                                <div class="fw-normal text-dark mb-1"><b>{{person.emp.emp_name}}</b></div>
                                <div class="text-gray small">
                                    {{person.emp.emp_code}} <br>
                                    ----
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </li>
        {% endfor %}
    </ul>
</div>

docapp/templates/docapp/doc_details_page_templates/doc_peoples_form.html
<tr {% if document_person_form.DELETE.value %} class="d-none" {%  endif %}>
    <td class="d-none">
        {{document_person_form.DELETE}}
    </td>
    <td>
        {{ document_person_form.person }}
        <div class="invalid-feedback">
            {{ document_person_form.person.errors }}
        </div>
    </td>
    <td>
        {{ document_person_form.print_order }}
        <div class="invalid-feedback">
            {{ document_person_form.print_order.errors }}
        </div>
    </td>
    <td>
        <button type="button" id="button_{{person_type}}_{{count_prefix}}_form" class="btn btn-danger d-inline-flex align-items-center"
            hx-on:click="removeForm(this,'{{person_type}}');">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-trash-fill" viewBox="0 0 16 16">
                <path
                    d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
            </svg>
        </button>
    </td>
</tr>

docapp/templates/docapp/doc_details_page_templates/doc_peoples_modal_form.html
<div class="modal-header">
    <h2 class="h6 modal-title">Add/Edit {{person_type_text}}</h2><button type="button" class="btn-close"
        data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form hx-post="{% url 'docapp:doceditpersontype' doc_id=doc_id person_type=person_type %}">
{% csrf_token %}
<div class="modal-body">
    
    {% if document_person_forms.non_form_errors %}
        <div class="alert alert-danger" role="alert">
            <ul>
                {% for error in document_person_forms.non_form_errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
   
    <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
            <thead class="thead-light">
                <tr>
                    <th style="width: 10%;" class="border-0 d-none">Delete</th>
                    <th style="width: 80%;" class="border-0 rounded-start">Employee Name</th>
                    <th style="width: 10%;" class="border-0">Order in {{person_type}} </th>
                    <th style="width: 5%;" class="border-0 rounded-end">Actions</th>
                </tr>
            </thead>
            {{ document_person_forms.management_form }}
            <tbody id="{{person_type}}_tablebody">
                {% for document_person_form in document_person_forms  %}
                    {% include 'docapp/doc_details_page_templates/doc_peoples_form.html' with document_person_form=document_person_form count_prefix=forloop.counter0 person_type=person_type %}
                {% endfor %}
            </tbody>
        </table>

       
    </div>


    <div class="mt-3 d-flex float-right">
        <button type="button" class="btn btn-success d-inline-flex align-items-center text-white ms-auto"
            hx-get="{% url 'docapp:docpersonnewform'  person_type=person_type %}"
            hx-include='#id_{{person_type}}-TOTAL_FORMS'
            hx-target="#{{person_type}}_tablebody"
            hx-swap="beforeend"
        >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-person-plus-fill mx-1" viewBox="0 0 16 16">
                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                <path fill-rule="evenodd"
                    d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5" />
            </svg>
            Add

        </button>
    </div>

</div>

</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-secondary">Submit</button>
    <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
</div>
</form>

docapp/templates/docapp/doc_details_page_templates/doc_project_reporttype_modal_form.html
<div class="modal-header">
    <h2 class="h6 modal-title">Edit Details of Entity/Project & Report Type</h2><button type="button" class="btn-close"
        data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form hx-post="{% url 'docapp:doceditentityreporttype' doc_id %}">
    {% csrf_token %}
    <div class="modal-body">
        <p class="card-text">
           {% if entity_report_type_form.errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for error in entity_report_type_form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            {% for field in entity_report_type_form %}
                <div class="fieldWrapper mt-3">
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
        </p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-secondary">Submit</button>
        <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
    </div>
</form>

docapp/templates/docapp/doc_details_page_templates/doc_title_abstract.html
<div class="mb-4">
    <div class="row align-items-center">

        <div class="col-auto ms--2">
            <h4 class="h6 mb-0">
                <label for="title">
                    Title
                </label>
            </h4>

        </div>
    </div>

    <textarea style="pointer-events: none;" class="form-control  flex-grow-1" id="title"
        rows="4">{{ doc.doc_title }}</textarea>
</div>

<div class="my-4">

    <div class="row align-items-center">

        <div class="col-auto ms--2">
            <h4 class="h6 mb-0">
                <label for="textarea">Abstract</label>
            </h4>

        </div>

    </div>

    {% if doc.abstract %}
    <textarea readonly style="width : 100%; " class="form-control" id="textarea"
        rows="8">{{ doc.abstract }}</textarea>
    {% else %}
    <textarea readonly style="width: 100%;" class="form-control" id="textarea"
        rows="8">No Abstract Available</textarea>
    {% endif %}



</div>
<div class="my-4">
    <div class="row mb-4">
        <div class="col-lg-6 col-sm-6">
            <label class="my-1 me-2" for="control_status">Control Status</label>
            <input style="pointer-events: none;" class="form-control" id="control_status"
                value="{{ doc.control_status }}">

        </div>
        <div class="col-lg-6 col-sm-6">
            <label class="my-1 me-2" for="security_classification">Security
                Classification</label>
            <input style="pointer-events: none;" class="form-control"
                id="security_classification" value="{{ doc.security_classification }}">
        </div>



    </div>
</div>

docapp/templates/docapp/doc_details_page_templates/doc_title_abstract_modal_form.html
<div class="modal-header">
    <h2 class="h6 modal-title">Edit Title/Abstract</h2><button type="button" class="btn-close" data-bs-dismiss="modal"
        aria-label="Close"></button>
</div>
<form hx-post="{% url 'docapp:doceditbasic' doc_id %}">
    <div class="modal-body">
        <p class="card-text">
            {% csrf_token %}
        <div class="mb-2">
            <label for="{{ form.doc_title.id_for_label }}"> Document Title: </label>
            {{ form.doc_title }}
            <div class="invalid-feedback">
                {{ form.doc_title.errors }}
            </div>
        </div>

        <div class="mb-2">
            <label for="{{ form.abstract.id_for_label }}"> Document Abstract: </label>
            {{ form.abstract }}
            <div class="invalid-feedback">
                {{ form.abstract.errors }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12 col-lg-6 col-sm-6 mb-1">
                <label class="my-1 me-2" for="{{ form.control_status.id_for_label }}">Control Status</label>
                {{ form.control_status }}
                <div class="invalid-feedback">
                    {{ form.control_status.errors }}
                </div>
            </div>
            <div class="col-12 col-lg-6 col-sm-6 mb-1">
                <label class="my-1 me-2" for="{{ form.security_classification.id_for_label }}">Security
                    Classification</label>
                {{ form.security_classification }}
                <div class="invalid-feedback">
                    {{ form.security_classification.errors }}
                </div>
            </div>
        </div>

        </p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-secondary">Submit</button>
        <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">Close</button>
    </div>
</form>

docapp/templates/docapp/doc_details_page_templates/modals.html
<div class="modal fade" id="modal_title_abstract" tabindex="-1" aria-labelledby="modal-default" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" id="modal_title_abstract_form" hx-target="this">
        </div>
    </div>
</div>

<div class="modal fade" id="modal_keywords" tabindex="-1" aria-labelledby="modal-default" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" id="modal_keywords_form" hx-target="this">
        </div>
    </div>
</div>

<div class="modal fade" id="modal_project_reporttypes" tabindex="-1" aria-labelledby="modal-default" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" id="modal_project_reporttypes_form" hx-target="this">
        </div>
    </div>
</div>

<div class="modal fade" id="modal_pages_references" tabindex="-1" aria-labelledby="modal-default" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" id="modal_pages_references_form" hx-target="this">
        </div>
    </div>
</div>

<div class="modal fade" id="modal_person_type" tabindex="-1" aria-labelledby="modal-default" style="display: none;"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" id="modal_person_type_form" hx-target="this">
        </div>
    </div>
</div>