docapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='docapp'
urlpatterns = [
    path("", views.index, name="index"),
    path("newdoc",views.newdoc, name="newdoc"),


    ############ URLS for page showing the list of Documents #############

    path("doclist/<str:person_type>",views.doclist,name="doc_list"),
    path("doclist/<str:person_type>/filtered", views.doclist_filtered, name="doc_list_filtered"),

    #######################################################################

    ############ URLS for page showing the details of a Document #############
    path("docdetails/<int:doc_id>", views.docdetails, name="docdetails"),
    
    # URLS for editing/adding details of a document

    ### BASIC DETAILS ##############
    path("doceditbasic/<int:doc_id>", views.doceditbasic, name="doceditbasic"),
    path("docgetbasic/<int:doc_id>", views.docgetbasic, name="docgetbasic"),
    ###############################

    ### KEYWORDS ##################
    path("doceditkeywords/<int:doc_id>",  views.doceditkeywords, name="doceditkeywords"),
    path("docgetkeywords/<int:doc_id>", views.docgetkeywords, name="docgetkeywords"),
    ################################

    ### ENTITY_REPORT_TYPE #######
    path("doceditprojectreporttype/<int:doc_id>", views.doceditentityreporttype, name="doceditentityreporttype"),
    path("docgetprojectreporttype/<int:doc_id>", views.docgetentityreporttype, name="docgetentityreporttype"),
    ###############################

    ### PERSON TYPE ##############
    path("doceditpersontype/<int:doc_id>/<str:person_type>", views.doceditpersontype, name="doceditpersontype"),
    path("docgetpersontype/<int:doc_id>/<str:person_type>", views.docgetpersontype, name="docgetpersontype"),
    path("docpersonnewform/<str:person_type>", views.doceditpersontype_get_blank_form, name="docpersonnewform"),
    path("docpersondelete/<int:docrolemapping_id>", views.docdeleteperson, name="docpersondelete" ),
    ###############################

    ### PAGES & REFERENCES ########
    path("doceditpagesreferences/<int:doc_id>", views.doceditpagesreferences, name="doceditpagesreferences"),
    path("docgetpagesreferences/<int:doc_id>", views.docgetpagesreferences, name="docgetpagesreferences"),

    ###############################
    

    path("docgeneratenumber/<int:doc_id>", views.docgeneratenumber, name="docgeneratenumber"),
    path("docupload/<int:doc_id>", views.docupload, name="docupload" ),
    ####################################

    path("submittolibrary/<int:doc_id>", views.submit_to_library, name="libsubmit"),
    path("viewdocument/<int:doc_id>", views.viewdocument, name="viewdocument"),
    path("viewpdfthumbnail/<int:doc_id>",views.viewpdfthumbnail, name="viewdocumentthumbnail"),
    
    ###################################

    path("docwithdraw/<int:doc_id>", views.docwithdraw, name="docwithdraw"),
    path("dateextension/<int:doc_id>", views.dateextension, name="dateextension"),

    ###################################

    path("settings", views.docsettings, name="docsettings"),

    ###############################
    path("error", views.error,name="error"),

    ################################
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docnumber_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docnumberapp/', include("docapp.urls"))
]

docapp/views.py
from django.shortcuts import redirect, render

from docapp.constants import DOC_NUMBER_DRAFT, DOC_NUMBER_STATUSES, DOC_NUMBER_USED, DOCUMENT_STATUSES, MEMBER_TYPES, DOCUMENT_ROLES, PDF_FILE_LOCATION
from docapp.constants import AUTHOR_CONSTANT, REVIEWER_CONSTANT, APPROVER_CONSTANT, CHECKED_BY_CONSTANT
from docapp.constants import AUTHOR_TEXT,REVIEWER_TEXT,APPROVER_TEXT,CHECKED_BY_TEXT, PERSON_CONSTANT_TO_TEXT_MAPPING
from docapp.constants import DOCUMENT_CONSTANT_TO_DB_MAPPING
from docapp.constants import DOC_DRAFT,DOC_PENDING_UPLOAD,DOC_UNDER_REVIEW,DOC_REUPLOAD,DOC_NUMBER_WITHDRAWN,DOC_COMPLETED
from docapp.constants import DOC_AUTHOR_CONSTANT, DOC_CHECKED_CONSTANT, DOC_APPROVER_CONSTANT, DOC_REVIEWER_CONSTANT
from docapp.constants import DOCUMENT_LIST_PAGE_SIZE, PDF_THUMBNAIL_LOCATION, NUM_EXTENSIONS_DAYS, LIMIT_EXTENSIONS

from .models import DocNumberSequence, Document, DocKeywordMapping, DocumentRoles, DocumentStatus, Employee, Keywords, DocumentNumber
from .models import DocumentNumberStatus, DocRoleMapping
from .forms import DocumentCreationForm, DocumentTitleAbstractForm, DocumentUploadForm
from .forms import DocumentKeywordsForm, DocumentEntityReportTypeForm, DocumentPagesReferencesForm
from .forms import DocumentAdvancedSearch, DocumentNumberSearch, DocumentPersonForm
from .forms import DocumentPersonBaseFormSet
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404

from django.forms import formset_factory
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator
from django.db import transaction
from django.urls import reverse
from django.conf import settings
import hashlib
import os
import fitz
# Create your views here.

#### Some View Related Constants ############

REDIRECT_URL = "docdetails/{0}"

# Dont change the left hand side of the dictionary
HX_TRIGGERS = {
    "basicdetails": "basicdetailschanged",
    "entityreporttype": "entityreporttypechanged",
    "keywords" : "keywordschanged",
    "pagesreferences": "pagesreferenceschanged",
    AUTHOR_CONSTANT : "authorschanged",
    REVIEWER_CONSTANT : "reviewerschanged",
    APPROVER_CONSTANT : "approverschanged",
    CHECKED_BY_CONSTANT : "checkedbychanged"
}

ADVANCED_SEARCH_FORM_SUBMIT_ID = 'advancedsearch_submit'
SIMPLE_SEARCH_FORM_SUBMIT_ID = 'simplesearch_submit'
ADVANCED_SEARCH_FORM_HIDDEN_FIELD = 'advancedsearch_form_hidden'
SIMPLE_SEARCH_FORM_HIDDEN_FIELD = 'simplesearch_form_hidden'

#ADVANCED_SEARCH_TOGGLE_NAME = 'search_toggle_button_hidden'
ADVANCED_SEARCH_TOGGLE_NAME = 'search_toggle_button'

##########################################


def index(request):
    return render(request, "docapp/index.html", {})


def save_people_data(formset, person_type, doc_id):
    try:
        person_db_value = DOCUMENT_CONSTANT_TO_DB_MAPPING[person_type]
        document = Document.objects.get(doc_id = doc_id)
        document_role = DocumentRoles.objects.filter(doc_role_short_code=person_db_value).first()

        formset_cleaned_data = []
        for form in formset:
            if 'DELETE' in form.cleaned_data:
                if (not form.cleaned_data['DELETE']):
                    formset_cleaned_data.append(form.cleaned_data)
            else:
                formset_cleaned_data.append(form.cleaned_data)          
                
        for form_data in formset_cleaned_data:
            if 'person' in form_data:
                person_doc_role = DocRoleMapping(
                    doc=document,
                    emp=form_data['person'],
                    empdisplay_name = "",
                    role=document_role,
                    print_order=form_data['print_order'],
                    role_status = 1
                ) 
                person_doc_role.save()
        return True
    except:
        return False

def generate_document_sequence_number(project, doc_type, current_year):
    
    STARTING_SEQUENCE_NUMBER = 1000
    try:
        docnumber_sequence = DocNumberSequence.objects.get(
                                doc_project = project,
                                doc_type = doc_type,
                                doc_year = current_year,
                                doc_sequence_active = 1
                            )
    except:
        docnumber_sequence = None
    
    if(docnumber_sequence is None):
        docnumber_sequence = DocNumberSequence(
                        doc_project = project,
                        doc_type = doc_type,
                        doc_year = current_year,
                        doc_sequence_active = 1,
                        doc_sequence_number = STARTING_SEQUENCE_NUMBER
            )
        docnumber_sequence.save()
    
    sequence_number =  docnumber_sequence.doc_sequence_number
    docnumber_sequence.doc_sequence_number = docnumber_sequence.doc_sequence_number + 1
    docnumber_sequence.save()

    return sequence_number

def get_non_field_form_error_messages(request,form, is_formset=True ):
    error_messages = []
    if is_formset:
        errors_list = form.non_form_errors()
    else:
        errors_list = form.non_field_errors()
    for error in errors_list:
        messages.add_message(request,messages.ERROR,error)
    
def handle_file_upload(doc_id,file):
    document = Document.objects.get(doc_id = doc_id)
    
    m = hashlib.sha256()
    document_number = document.document_number
    document_number = document_number.replace("/","_")

    # Hash for document content
    content_to_encrypt = document_number + "_" + document.doc_title + "#" + document.abstract
    m.update(str.encode(content_to_encrypt))
    hex_digest = m.hexdigest()

    file_name = document_number + "_" + hex_digest + ".pdf"
    complete_path = os.path.join(PDF_FILE_LOCATION,file_name)
    if not os.path.exists(PDF_FILE_LOCATION):
        os.makedirs(PDF_FILE_LOCATION)
        
    with open(complete_path,"wb+") as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    
    # Generate Thumbnail
    pdf_document = fitz.open(complete_path)
    first_page = pdf_document[0]
    rect = fitz.Rect(0, 0, first_page.rect.width,first_page.rect.height)
    #first_page.add_rect_annot(rect)
    shape=first_page.new_shape()
    shape.draw_rect(rect)
    shape.finish(color=(0, 0, 0),width=2.5)
    shape.commit()
    image = first_page.get_pixmap()
    if not os.path.exists(PDF_THUMBNAIL_LOCATION):
        os.makedirs(PDF_THUMBNAIL_LOCATION)    

    image_path = os.path.join(PDF_THUMBNAIL_LOCATION,document_number + ".png")
    image.save(image_path)
    
    return (complete_path,image_path)

def newdoc(request):
    if request.method == "POST":
        form  = DocumentCreationForm(request.POST)
        report_type_form = DocumentEntityReportTypeForm(request.POST)
        
        DocumentPersonFormSet = formset_factory(DocumentPersonForm,formset=DocumentPersonBaseFormSet,extra=1, can_delete=True)
        author_formset = DocumentPersonFormSet(request.POST, prefix=AUTHOR_CONSTANT)
        reviewer_formset = DocumentPersonFormSet(request.POST,prefix = REVIEWER_CONSTANT)
        approver_formset = DocumentPersonFormSet(request.POST, prefix=APPROVER_CONSTANT)
        checkedby_formset = DocumentPersonFormSet(request.POST,prefix=CHECKED_BY_CONSTANT)

        # Reduce the below paragraph of code with a few lines
        form_valid = form.is_valid()
        report_type_form_valid = report_type_form.is_valid()
        author_formset_valid = author_formset.is_valid()
        reviewer_formset_valid = reviewer_formset.is_valid()
        approver_formset_valid = approver_formset.is_valid()
        # IGNORED AS OF NOW
        checkedby_formset_valid = checkedby_formset.is_valid()
        
        # Check if all entries are true
        if(form_valid==report_type_form_valid==author_formset_valid==reviewer_formset_valid==approver_formset_valid==True):

            doc_status_object = None
            doc_number_status_object = None
          
            if 'generate' in request.POST:
                doc_status_object = DocumentStatus.objects.get(doc_status_name=DOCUMENT_STATUSES[1][0])
                doc_number_status_object = DocumentNumberStatus.objects.get(doc_num_status_name=DOC_NUMBER_STATUSES[1][0])
            else:
                doc_status_object = DocumentStatus.objects.get(doc_status_name=DOCUMENT_STATUSES[0][0])
                doc_number_status_object = DocumentNumberStatus.objects.get(doc_num_status_name=DOC_NUMBER_STATUSES[0][0] )

            try:
                with transaction.atomic():
                        new_document = Document.objects.create(
                            doc_title=form.cleaned_data['doc_title'],
                            control_status=form.cleaned_data['control_status'],
                            security_classification=form.cleaned_data['security_classification'],
                            doc_type_general=form.cleaned_data['doc_type_general'],
                            doc_status=doc_status_object
                        )

                        new_document.parent_doc = new_document
                        new_document.save()

                        save_people_data(author_formset,AUTHOR_CONSTANT,new_document.doc_id)
                        save_people_data(reviewer_formset,REVIEWER_CONSTANT,new_document.doc_id)
                        save_people_data(approver_formset,APPROVER_CONSTANT,new_document.doc_id)
                        
                        if('generate' in request.POST):
                            current_year = timezone.now().year
                            sequence_number = generate_document_sequence_number(report_type_form.cleaned_data['doc_project'],report_type_form.cleaned_data['doc_type'],current_year)
                            doc_number = DocumentNumber.objects.create(
                                doc=new_document,

docapp/templates/docapp/error_page.html
{% extends "docapp/base.html" %}
{% block content %}
{% load static %}

{% endblock %}

docapp/templates/docapp/index.html
{% extends "docapp/base.html" %}

{% block content %}
{% load static %}
<!-- <button class="btn btn-primary" type="button">Regular</button> -->
<div class="my-4">
     <div class="row">
          <div class="col-12 col-sm-6 col-xl-4 mb-4">
               <div class="card border-0 shadow">
                    <div class="card-body">
                         <canvas id="myChart"  height="400"></canvas>
                    </div>
               </div>
          </div>
          <div class="col-12 col-sm-6 col-xl-8 mb-4">
               <div class="card border-0 shadow">
                    <div class="card-body">
                         <canvas id="myChart2"  height="400"></canvas>
                    </div>
               </div>
          </div>
     
     </div>
</div>




<script src="{% static 'docapp/vendor/chartjs/chart.js' %}"></script>

<script>
     const ctx = document.getElementById('myChart');
     const ctx2 = document.getElementById('myChart2');
     new Chart(ctx, {
          type: 'bar',
          data: {
               labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
               datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: '#F26430BB',
                    borderWidth: 1
               }]
          },
          
          options: {
               responsive: true,
               maintainAspectRatio: false,
               plugins: {
                    title: {
                         display: true,
                         text: 'Custom Chart Title',
                         font: {
                              size: 25,
                         }
                    }
               },
               scales: {
                    y: {
                         beginAtZero: true
                    }
               }
          }
     });

     new Chart(ctx2, {
          type: 'line',
          data: {
               labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange','Cyan'],
               datasets: [{
               label: 'My First Dataset',
               data: [65, 59, 80, 81, 56, 55, 40],
               fill: false,
               borderColor: 'rgb(75, 192, 192)',
               tension: 0.1
               }]
          },
          options: {
               responsive: true,
               maintainAspectRatio: false,
              
          }
          
     });
</script>
{% endblock %}

docapp/templates/docapp/new_doc.html
{% extends "docapp/base.html" %}
{% load static %}
{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'docapp/css/doc_new.css' %}">
{% endblock %}
{% block content %}
<nav aria-label="breadcrumb" class="d-none d-md-inline-block">
  <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
    <li class="breadcrumb-item">
      <a href="{% url 'docapp:index' %}">
        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
          </path>
        </svg>
      </a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      <a href="#">New Document</a>
    </li>

  </ol>
</nav>
{% if messages %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
      {% for message in messages %}
        <li>{{message}}</li>
      {% endfor %}
    </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}


<form method="POST" action="{% url 'docapp:newdoc' %}">
  {% csrf_token %}
<div class="card mb-10">
  <div class="card-body">
    <div class="row g-0">
      <div class="col-md-4">
        <img style="opacity: 0.7; height: 95%;" src="{% static 'docapp/assets/img/doc_new.jpeg'%}"
          class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8 d-flex align-items-center">
        <div style="padding: 0.9rem 0.9rem;" class="card-body">
          <h3 class="card-title">
            <center>
              New Document Details
            </center>
          </h3>
          <hr>
          <p class="card-text">Enter the basic details of the new document to be submitted</p>
       
            <p class="card-text">
  
            <div class="mb-1">
              <label for="{{ form.doc_title.id_for_label }}"> Title </label>
              {{ form.doc_title }}
              <div class="invalid-feedback">
               {{ form.doc_title.errors }}
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-12 col-lg-6 col-sm-6 mb-1">
                <label class="my-1 me-2" for="{{ form.control_status.id_for_label }}">Control Status</label>
                {{ form.control_status }}
                <div class="invalid-feedback">
                  {{ form.control_status.errors }}
                </div>
              </div>
              <div class="col-12 col-lg-6 col-sm-6 mb-1">
                <label class="my-1 me-2" for="{{ form.security_classification.id_for_label }}">Security
                  Classification</label>
                {{ form.security_classification }}
                <div class="invalid-feedback">
                  {{ form.security_classification.errors }}
                </div>
              </div>
            </div>
  
            <div class="row mb-4">
              <div class="col-lg-12 col-sm-12">
                <label class="mb-1 me-2" for="{{ form.doc_type_general.id_for_label }}">Whether it is an Entity/Project
                  Report</label>
                {{ form.doc_type_general }}
                <div class="invalid-feedback">
                  {{ form.doc_type_general.errors }}
                </div>
              </div>
            </div>
            </p>
        </div>
      </div>
    </div>
    <div class="row g-0 mt-lg-0 mt-md-1 mt-ms-0">
      <div class="col-lg-6 col-md-6 col-sm-6 col-12 px-1">
        <label class="my-1 me-2" for="{{ report_type_form.doc_project.id_for_label }}">Entity/Project Name</label>
        {{ report_type_form.doc_project }}
        <div class="invalid-feedback">
          {{ report_type_form.doc_project.errors }}
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-12 px-1">
        <label class="my-1 me-2" for="{{ report_type_form.doc_type.id_for_label }}">Type Of Document</label>
        {{ report_type_form.doc_type }}
        <div class="invalid-feedback">
          {{ report_type_form.doc_type.errors }}
        </div>
      </div>
    </div>

    <hr>

    <div class="row g-0">
      <div class="col-lg-6 col-md-6 col-sm-6 col-12 px-1 mb-2">
        <div class="card">
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Author(s)</h6>
            <p class="card-text">
              <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light">
                        <tr>
                            <th style="width: 1%;" class="border-0 d-none">Delete</th>
                            <th style="width: 70%;" class="border-0 rounded-start">Employee Name</th>
                            <th style="width: 15%;" class="border-0">Order in {{person_type}} </th>
                            <th style="width: 1%;" class="border-0 rounded-end">Actions</th>
                        </tr>
                    </thead>
                    {{ author_formset.management_form }}
                    <tbody id="{{AUTHOR_CONSTANT}}_tablebody">
                      {% for author_form in author_formset %}
                          {% include 'docapp/doc_details_page_templates/doc_peoples_form.html' with document_person_form=author_form count_prefix=forloop.counter0 person_type=AUTHOR_CONSTANT %}
                      {% endfor %}
                    </tbody>
                </table>
              </div>
            </p>
            <a  class="card-link ms-auto float-end">
              <button type="button" class="btn btn-outline-info"
                hx-get="{% url 'docapp:docpersonnewform'  person_type=AUTHOR_CONSTANT %}"
                hx-include='#id_{{AUTHOR_CONSTANT}}-TOTAL_FORMS'
                hx-target="#{{AUTHOR_CONSTANT}}_tablebody"
                hx-swap="beforeend"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                  <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"></path>
                  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"></path>
                </svg>
                Add Author
              </button>
            </a>
         
         
          </div>
        </div>        
      </div>

      <div class="col-lg-6 col-md-6 col-sm-6 col-12 px-1 mb-2">
        <div class="card">
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Reviewer(s)</h6>
            <p class="card-text">
              <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light">
                        <tr>
                            <th style="width: 10%;" class="border-0 d-none">Delete</th>
                            <th style="width: 80%;" class="border-0 rounded-start">Employee Name</th>
                            <th style="width: 10%;" class="border-0">Order in {{person_type}} </th>
                            <th style="width: 5%;" class="border-0 rounded-end">Actions</th>
                        </tr>
                    </thead>
                    {{reviewer_formset.management_form}}
                    <tbody id="{{REVIEWER_CONSTANT}}_tablebody">
                      {% for reviewer_form in reviewer_formset %}
                          {% include 'docapp/doc_details_page_templates/doc_peoples_form.html' with document_person_form=reviewer_form count_prefix=forloop.counter0 person_type=REVIEWER_CONSTANT %}
                      {% endfor %}
                    </tbody>
                </table>
              </div>
            </p>
            <a  class="card-link ms-auto float-end">
              <button type="button" class="btn btn-outline-info"
                hx-get="{% url 'docapp:docpersonnewform'  person_type=REVIEWER_CONSTANT %}"
                hx-include='#id_{{REVIEWER_CONSTANT}}-TOTAL_FORMS'
                hx-target="#{{REVIEWER_CONSTANT}}_tablebody"
                hx-swap="beforeend"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                  <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"></path>
                  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"></path>
                </svg>
                Add Reviewer
              </button>
            </a>
         
          </div>
        </div>        
      </div>

      <div class="col-lg-6 col-md-6 col-sm-6 col-12 px-1 mb-2">
        <div class="card">
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Approver(s)</h6>
            <p class="card-text">
              <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light">
                        <tr>
                            <th style="width: 10%;" class="border-0 d-none">Delete</th>
                            <th style="width: 80%;" class="border-0 rounded-start">Employee Name</th>
                            <th style="width: 10%;" class="border-0">Order in {{person_type}} </th>
                            <th style="width: 5%;" class="border-0 rounded-end">Actions</th>
                        </tr>
                    </thead>
                    {{approver_formset.management_form}}
                    <tbody id="{{APPROVER_CONSTANT}}_tablebody">
                      {% for approver_form in approver_formset %}
                          {% include 'docapp/doc_details_page_templates/doc_peoples_form.html' with document_person_form=approver_form count_prefix=forloop.counter0 person_type=APPROVER_CONSTANT %}
                      {% endfor %}
                    </tbody>
                </table>
              </div>
            </p>
            <a  class="card-link ms-auto float-end">
              <button type="button" class="btn btn-outline-info"
                hx-get="{% url 'docapp:docpersonnewform'  person_type=APPROVER_CONSTANT %}"
                hx-include='#id_{{APPROVER_CONSTANT}}-TOTAL_FORMS'
                hx-target="#{{APPROVER_CONSTANT}}_tablebody"
                hx-swap="beforeend"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                  <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"></path>
                  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"></path>
                </svg>
                Add Approver
              </button>
            </a>
          </div>
        </div>        
      </div>


    </div>
    <hr/>
    <button type="submit" name="draft" class="btn btn-secondary my-1" type="button">Save as Draft</button>
    <button type="submit" name="generate" style="color: white;" class="btn btn-success my-1" type="button">Generate Document Number</button>
  </div>
</div>
</form>

<!--
<small class="text-info">
              <b> NB: Once you press submit, document will be available under
                <span class="text-danger">Your Documents > Author </span> 
                for further edits </b>
            </small>
            <center style="margin-top: 30px;">
              <button type="submit" class="btn  btn-secondary" type="button">SUBMIT DETAILS</button>
            </center>

-->
{% endblock %}

{% block scripts %}
<script src="{% static 'docapp/js/doc_new.js' %}"></script>
{% endblock %}

docapp/templates/docapp/settings.html
{% extends "docapp/base.html" %}
{% load static %}
{% block content %}

{% endblock %}